import { Lead, LeadList, UserProfile, Brand, Account, Campaign, Meeting, LeadActivity, Reminder, InAppNotification, MailMergeBatch } from '../types';

export const INITIAL_LISTS: LeadList[] = [
  { id: 'list-1', name: 'UK Tech Outbound', description: 'Priority outreach for UK tech founders and directors', color: '#00C2FF', created_at: '2026-09-01T00:00:00Z' },
  { id: 'list-2', name: 'Enterprise August', description: 'Enterprise tier prospects for Q3 training contracts', color: '#00E5A0', created_at: '2026-09-01T00:00:00Z' },
  { id: 'list-3', name: 'High Priority Followups', description: 'Active prospects needing WhatsApp & call followups', color: '#F97316', created_at: '2026-09-02T00:00:00Z' },
];

export const INITIAL_USERS: UserProfile[] = [
  { id: 'usr-ruhit', email: 'ruhit@ros.com', full_name: 'Ruhit', role: 'admin', avatar_color: '#00C2FF' },
  { id: 'usr-nayeemur', email: 'nayeemur@ros.com', full_name: 'Nayeemur', role: 'team_member', avatar_color: '#00E5A0' },
  { id: 'usr-farzan', email: 'farzan@trainingexpress.org.uk', full_name: 'Farzan Hussain', role: 'manager', avatar_color: '#3B82F6' },
  { id: 'usr-kamran', email: 'kamran@thamescollege.org', full_name: 'Kamran Hussain', role: 'manager', avatar_color: '#8B5CF6' },
  { id: 'usr-sagar', email: 'sagar@johnacademy.co.uk', full_name: 'Sagar Ali', role: 'team_member', avatar_color: '#F97316' },
  { id: 'usr-anis', email: 'anis@oneeducation.org.uk', full_name: 'Anisur Rahman', role: 'team_member', avatar_color: '#EC4899' },
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'br-1', name: 'Training Express', website: 'https://trainingexpress.org.uk', status: 'active' },
  { id: 'br-2', name: 'John Academy', website: 'https://johnacademy.co.uk', status: 'active' },
  { id: 'br-3', name: 'One Education', website: 'https://oneeducation.org.uk', status: 'active' },
  { id: 'br-4', name: 'Thames College', website: 'https://thamescollege.org', status: 'active' },
  { id: 'br-5', name: 'Apex Learning', website: 'https://apexlearning.org.uk', status: 'active' },
  { id: 'br-6', name: 'Alpha Academy', website: 'https://alphaacademy.org', status: 'active' },
  { id: 'br-7', name: 'Janets', website: 'https://janets.org.uk', status: 'active' },
  { id: 'br-8', name: 'iStudy', website: 'https://istudy.org.uk', status: 'active' },
  { id: 'br-9', name: 'Cambridge Open Academy', website: 'https://cambridgeopenacademy.com', status: 'active' },
  { id: 'br-10', name: 'Skill Up', website: 'https://skillup.org.uk', status: 'active' },
];

export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'acc-1', account_name: 'Farzan TX', email_account: 'farzan@trainingexpress.org.uk', sender_name: 'Farzan Hussain', brand_id: 'br-1', brand_name: 'Training Express', status: 'active' },
  { id: 'acc-2', account_name: 'Collab JA', email_account: 'collaboration@johnacademy.co.uk', sender_name: 'Farzan Hussain', brand_id: 'br-2', brand_name: 'John Academy', status: 'active' },
  { id: 'acc-3', account_name: 'Business OE', email_account: 'business@oneeducation.org.uk', sender_name: 'Anisur Rahman', brand_id: 'br-3', brand_name: 'One Education', status: 'active' },
  { id: 'acc-4', account_name: 'Thames College', email_account: 'business@thamescollege.org', sender_name: 'Kamran Hussain', brand_id: 'br-4', brand_name: 'Thames College', status: 'active' },
  { id: 'acc-5', account_name: 'Corp JA', email_account: 'corporate@johnacademy.co.uk', sender_name: 'Farzan Hussain', brand_id: 'br-2', brand_name: 'John Academy', status: 'active' },
  { id: 'acc-6', account_name: 'Enterprise TX', email_account: 'enterprise@trainingexpress.org.uk', sender_name: 'Farzan Hussain', brand_id: 'br-1', brand_name: 'Training Express', status: 'active' },
  { id: 'acc-7', account_name: 'B2B TX', email_account: 'b2b@trainingexpress.org.uk', sender_name: 'Farzan Hussain', brand_id: 'br-1', brand_name: 'Training Express', status: 'active' },
  { id: 'acc-8', account_name: 'Anis OE', email_account: 'anis@oneeducation.org.uk', sender_name: 'Anisur Rahman', brand_id: 'br-3', brand_name: 'One Education', status: 'active' },
  { id: 'acc-9', account_name: 'Corp APX', email_account: 'corporate@apexlearning.org.uk', sender_name: 'Kamran Hussain', brand_id: 'br-5', brand_name: 'Apex Learning', status: 'active' },
  { id: 'acc-10', account_name: 'Partner ALP', email_account: 'partnership@alphaacademy.org', sender_name: 'Kamran Hussain', brand_id: 'br-6', brand_name: 'Alpha Academy', status: 'active' },
  { id: 'acc-11', account_name: 'Sagar JA', email_account: 'sagar@johnacademy.co.uk', sender_name: 'Sagar Ali', brand_id: 'br-2', brand_name: 'John Academy', status: 'active' },
  { id: 'acc-12', account_name: 'B2B JNTS', email_account: 'b2b@janets.org.uk', sender_name: 'Kamran Hussain', brand_id: 'br-7', brand_name: 'Janets', status: 'active' },
  { id: 'acc-13', account_name: 'iSutdyt', email_account: 'Muhammad@istudy.org.uk', sender_name: 'Kamran Hussain', brand_id: 'br-8', brand_name: 'iStudy', status: 'active' },
  { id: 'acc-14', account_name: 'Business CMB', email_account: 'business@cambridgeopenacademy.com', sender_name: 'Kamran Hussain', brand_id: 'br-9', brand_name: 'Cambridge Open Academy', status: 'active' },
  { id: 'acc-15', account_name: 'Business TX', email_account: 'business@trainingexpress.org.uk', sender_name: 'Kamran Hussain', brand_id: 'br-1', brand_name: 'Training Express', status: 'active' },
  { id: 'acc-16', account_name: 'Collab TX', email_account: 'collaboration@trainingexpress.org.uk', sender_name: 'Farzan Hussain', brand_id: 'br-1', brand_name: 'Training Express', status: 'active' },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  { id: 'cmp-1', name: 'Follow Up Email', brand_id: 'br-1', account_id: 'acc-1', status: 'Active' },
  { id: 'cmp-2', name: 'UNI Campaign', brand_id: 'br-4', account_id: 'acc-4', status: 'Active' },
  { id: 'cmp-3', name: 'Email Campaign', brand_id: 'br-3', account_id: 'acc-3', status: 'Active' },
  { id: 'cmp-4', name: 'B2B Outbound Q3', brand_id: 'br-1', account_id: 'acc-7', status: 'Active' },
  { id: 'cmp-5', name: 'Care Campaign UK', brand_id: 'br-2', account_id: 'acc-2', status: 'Active' },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    email: 'admin@languageinstituten.com',
    first_name: 'Solomon',
    last_name: 'Kariuki',
    company_name: 'Language Institute',
    alternative_phone: '+254712345678',
    list_ids: ['list-1'],
    country: 'Kenya',
    city: 'Nairobi',
    priority: 'High',
    campaign_id: 'cmp-1',
    campaign_name: 'Follow Up Email',
    brand_id: 'br-1',
    brand_name: 'Training Express',
    account_id: 'acc-1',
    account_name: 'Farzan TX',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    is_interested: true,
    interested_at: '2026-09-01T09:00:00.000Z',
    is_meeting_scheduled: true,
    meeting_scheduled_at: '2026-09-02T11:00:00.000Z',
    is_meeting_done: false,
    meeting_count_type: null,
    is_pending: false,
    meeting_date: '2026-09-08',
    meeting_time: '14:00',
    meeting_timezone: 'Asia/Dhaka',
    meeting_type: 'Google Meet',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    tags: ['Hot', 'Corporate'],
    created_at: '2026-09-01T08:00:00.000Z',
    updated_at: '2026-09-02T11:00:00.000Z'
  },
  {
    id: 'lead-2',
    email: 'info@workplacesafetygroup.co.uk',
    first_name: 'Paul',
    last_name: 'Henderson',
    company_name: 'Workplace Safety Group',
    whatsapp_number: '+443333208568',
    alternative_phone: '+442079460123',
    list_ids: ['list-1', 'list-2'],
    country: 'United Kingdom',
    city: 'London',
    priority: 'High',
    campaign_id: 'cmp-2',
    campaign_name: 'UNI Campaign',
    brand_id: 'br-2',
    brand_name: 'John Academy',
    account_id: 'acc-2',
    account_name: 'Collab JA',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    is_interested: true,
    interested_at: '2026-09-01T10:30:00.000Z',
    is_meeting_scheduled: true,
    meeting_scheduled_at: '2026-09-02T14:00:00.000Z',
    is_meeting_done: true,
    meeting_done_at: '2026-09-03T15:00:00.000Z',
    meeting_count_type: 'YES',
    meeting_count_at: '2026-09-03T15:30:00.000Z',
    is_pending: false,
    tags: ['Closed Won', 'High Priority'],
    created_at: '2026-09-01T10:00:00.000Z',
    updated_at: '2026-09-03T15:30:00.000Z'
  },
  {
    id: 'lead-3',
    email: 'info@simonmorrell.com',
    first_name: 'Simon',
    last_name: 'Morrell',
    company_name: 'Simon Morrell Coaching',
    whatsapp_number: '+447484331572',
    country: 'United Kingdom',
    city: 'Cardiff',
    priority: 'Medium',
    campaign_id: 'cmp-2',
    campaign_name: 'UNI Campaign',
    brand_id: 'br-4',
    brand_name: 'Thames College',
    account_id: 'acc-4',
    account_name: 'Thames College',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    is_interested: true,
    interested_at: '2026-09-02T08:00:00.000Z',
    is_meeting_scheduled: true,
    meeting_scheduled_at: '2026-09-03T10:00:00.000Z',
    is_meeting_done: true,
    meeting_done_at: '2026-09-04T12:00:00.000Z',
    meeting_count_type: 'NO', // Meeting Count = NO, but Meeting Done = YES!
    meeting_count_at: '2026-09-04T12:30:00.000Z',
    is_pending: true, // Independent pending follow up
    pending_at: '2026-09-04T12:35:00.000Z',
    notes: 'Meeting happened. Budget constraints for Q3. Pending follow up in 2 weeks.',
    tags: ['Follow-up'],
    created_at: '2026-09-02T08:00:00.000Z',
    updated_at: '2026-09-04T12:35:00.000Z'
  },
  {
    id: 'lead-4',
    email: 'info@swahilicourses.co.tz',
    first_name: 'Martin',
    last_name: 'Mtemi',
    company_name: 'Swahili Learning Co',
    whatsapp_number: '+255739621510',
    country: 'Tanzania',
    city: 'Dar es Salaam',
    priority: 'High',
    campaign_id: 'cmp-3',
    campaign_name: 'Email Campaign',
    brand_id: 'br-1',
    brand_name: 'Training Express',
    account_id: 'acc-1',
    account_name: 'Farzan TX',
    assigned_user_id: 'usr-nayeemur',
    assigned_user_name: 'Nayeemur',
    is_interested: true,
    interested_at: '2026-09-03T09:15:00.000Z',
    is_meeting_scheduled: true,
    meeting_scheduled_at: '2026-09-04T11:00:00.000Z',
    is_meeting_done: false,
    meeting_count_type: null,
    is_pending: false,
    meeting_date: '2026-09-05', // in the past -> Missed meeting!
    meeting_time: '15:00',
    tags: ['Hot'],
    created_at: '2026-09-03T09:00:00.000Z',
    updated_at: '2026-09-04T11:00:00.000Z'
  },
  {
    id: 'lead-5',
    email: 'info@digitaxbs.co.za',
    first_name: 'Nyasha',
    last_name: 'Chikwanha',
    company_name: 'DigiTax Business Solutions',
    whatsapp_number: '+27870309089',
    country: 'South Africa',
    city: 'Johannesburg',
    priority: 'Medium',
    campaign_id: 'cmp-3',
    campaign_name: 'Email Campaign',
    brand_id: 'br-10',
    brand_name: 'Skill Up',
    account_id: 'acc-3',
    account_name: 'Business OE',
    assigned_user_id: 'usr-nayeemur',
    assigned_user_name: 'Nayeemur',
    is_interested: true,
    interested_at: '2026-09-03T11:00:00.000Z',
    is_meeting_scheduled: true,
    meeting_scheduled_at: '2026-09-04T13:00:00.000Z',
    is_meeting_done: true,
    meeting_done_at: '2026-09-04T16:00:00.000Z',
    meeting_count_type: 'YES',
    meeting_count_at: '2026-09-04T16:15:00.000Z',
    is_pending: false,
    tags: ['Corporate'],
    created_at: '2026-09-03T10:00:00.000Z',
    updated_at: '2026-09-04T16:15:00.000Z'
  },
  {
    id: 'lead-6',
    email: 'r.steeles@securehealthcaresolutions.co.uk',
    first_name: 'Robbie',
    last_name: 'Steeles',
    company_name: 'Secure Healthcare Solutions',
    country: 'United Kingdom',
    city: 'Wolverhampton',
    priority: 'Medium',
    campaign_id: 'cmp-5',
    campaign_name: 'Care Campaign UK',
    brand_id: 'br-2',
    brand_name: 'John Academy',
    account_id: 'acc-2',
    account_name: 'Collab JA',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    is_interested: false,
    is_meeting_scheduled: false,
    is_meeting_done: false,
    meeting_count_type: null,
    is_pending: false,
    created_at: '2026-08-25T09:00:00.000Z',
    updated_at: '2026-08-25T09:00:00.000Z'
  },
  {
    id: 'lead-7',
    email: 'stephen.mander@serenitycaresolent.co.uk',
    first_name: 'Steve',
    last_name: 'Mander',
    company_name: 'Serenity Care Solent Limited',
    country: 'United Kingdom',
    city: 'Gosport',
    priority: 'Medium',
    campaign_id: 'cmp-5',
    campaign_name: 'Care Campaign UK',
    brand_id: 'br-2',
    brand_name: 'John Academy',
    account_id: 'acc-2',
    account_name: 'Collab JA',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    is_interested: false,
    is_meeting_scheduled: false,
    is_meeting_done: false,
    meeting_count_type: null,
    is_pending: false,
    created_at: '2026-08-25T09:15:00.000Z',
    updated_at: '2026-08-25T09:15:00.000Z'
  }
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: 'act-1',
    lead_id: 'lead-1',
    activity_type: 'Interested',
    description: 'Lead responded expressing interest in corporate training package',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-01T09:00:00.000Z'
  },
  {
    id: 'act-2',
    lead_id: 'lead-1',
    activity_type: 'WhatsApp Sent',
    description: 'Shared introductory brochure via WhatsApp',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-01T10:00:00.000Z'
  },
  {
    id: 'act-3',
    lead_id: 'lead-1',
    activity_type: 'Meeting Scheduled',
    description: 'Scheduled discovery call for Sep 08, 14:00 (Asia/Dhaka)',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-02T11:00:00.000Z'
  },
  {
    id: 'act-4',
    lead_id: 'lead-2',
    activity_type: 'Meeting Done',
    description: 'Discovery session completed successfully with Managing Director',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-03T15:00:00.000Z'
  },
  {
    id: 'act-5',
    lead_id: 'lead-2',
    activity_type: 'Meeting Count YES',
    description: 'Qualified meeting confirmed towards Monthly Meeting Count',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-03T15:30:00.000Z'
  },
  {
    id: 'act-6',
    lead_id: 'lead-3',
    activity_type: 'Meeting Done',
    description: 'Meeting held with Simon Morrell',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-04T12:00:00.000Z'
  },
  {
    id: 'act-7',
    lead_id: 'lead-3',
    activity_type: 'Meeting Count NO',
    description: 'Meeting completed but disqualified for count (budget constraints)',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-04T12:30:00.000Z'
  },
  {
    id: 'act-8',
    lead_id: 'lead-3',
    activity_type: 'Pending YES',
    description: 'Marked Pending YES for mid-September follow up',
    user_id: 'usr-ruhit',
    user_name: 'Ruhit',
    created_at: '2026-09-04T12:35:00.000Z'
  },
  {
    id: 'act-9',
    lead_id: 'lead-4',
    activity_type: 'Meeting Missed',
    description: 'Prospect did not attend scheduled call on Sep 05 at 15:00',
    user_id: 'usr-nayeemur',
    user_name: 'Nayeemur',
    created_at: '2026-09-05T15:30:00.000Z'
  }
];

export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'mtg-1',
    lead_id: 'lead-1',
    lead_name: 'Solomon Kariuki',
    lead_company: 'Language Institute',
    lead_email: 'admin@languageinstituten.com',
    campaign_name: 'Follow Up Email',
    brand_name: 'Training Express',
    account_name: 'Farzan TX',
    scheduled_at: '2026-09-08T08:00:00.000Z',
    duration_minutes: 30,
    status: 'scheduled',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    created_at: '2026-09-02T11:00:00.000Z',
    updated_at: '2026-09-02T11:00:00.000Z'
  },
  {
    id: 'mtg-2',
    lead_id: 'lead-4',
    lead_name: 'Martin Mtemi',
    lead_company: 'Swahili Learning Co',
    lead_email: 'info@swahilicourses.co.tz',
    campaign_name: 'Email Campaign',
    brand_name: 'Training Express',
    account_name: 'Farzan TX',
    scheduled_at: '2026-09-05T09:00:00.000Z', // past
    duration_minutes: 45,
    status: 'missed',
    notes: 'Did not join call. Sent follow up email & WhatsApp.',
    assigned_user_id: 'usr-nayeemur',
    assigned_user_name: 'Nayeemur',
    created_at: '2026-09-04T11:00:00.000Z',
    updated_at: '2026-09-05T15:30:00.000Z'
  },
  {
    id: 'mtg-3',
    lead_id: 'lead-2',
    lead_name: 'Paul Henderson',
    lead_company: 'Workplace Safety Group',
    lead_email: 'info@workplacesafetygroup.co.uk',
    campaign_name: 'UNI Campaign',
    brand_name: 'John Academy',
    account_name: 'Collab JA',
    scheduled_at: '2026-09-03T09:00:00.000Z',
    duration_minutes: 30,
    status: 'done',
    outcome: 'meeting_count_yes',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    created_at: '2026-09-02T14:00:00.000Z',
    updated_at: '2026-09-03T15:30:00.000Z'
  },
  {
    id: 'mtg-4',
    lead_id: 'lead-3',
    lead_name: 'Simon Morrell',
    lead_company: 'Simon Morrell Coaching',
    lead_email: 'info@simonmorrell.com',
    campaign_name: 'UNI Campaign',
    brand_name: 'Thames College',
    account_name: 'Thames College',
    scheduled_at: '2026-09-04T06:00:00.000Z',
    duration_minutes: 30,
    status: 'done',
    outcome: 'meeting_count_no',
    assigned_user_id: 'usr-ruhit',
    assigned_user_name: 'Ruhit',
    created_at: '2026-09-03T10:00:00.000Z',
    updated_at: '2026-09-04T12:30:00.000Z'
  }
];

export const INITIAL_REMINDERS: Reminder[] = [
  {
    id: 'rem-1',
    lead_id: 'lead-3',
    lead_name: 'Simon Morrell',
    lead_company: 'Simon Morrell Coaching',
    reminder_type: 'Follow-up Call',
    reminder_date: '2026-09-10',
    reminder_time: '14:00',
    note: 'Call Simon to check if revised Q4 training budget is confirmed',
    user_id: 'usr-ruhit',
    is_completed: false,
    created_at: '2026-09-04T12:40:00.000Z'
  },
  {
    id: 'rem-2',
    lead_id: 'lead-4',
    lead_name: 'Martin Mtemi',
    lead_company: 'Swahili Learning Co',
    reminder_type: 'Reschedule Outreach',
    reminder_date: '2026-09-07',
    reminder_time: '11:00',
    note: 'Send WhatsApp reminder for missed meeting rescheduling',
    user_id: 'usr-nayeemur',
    is_completed: false,
    created_at: '2026-09-05T16:00:00.000Z'
  }
];

export const INITIAL_NOTIFICATIONS: InAppNotification[] = [
  {
    id: 'notif-1',
    title: 'Missed Meeting Alert',
    message: 'Martin Mtemi (Swahili Learning Co) did not attend scheduled call on Sep 05.',
    type: 'meeting_missed',
    is_read: false,
    created_at: '2026-09-05T15:30:00.000Z'
  },
  {
    id: 'notif-2',
    title: 'Upcoming Meeting in 2 Days',
    message: 'Discovery session with Solomon Kariuki (Language Institute) scheduled for Sep 08 at 14:00.',
    type: 'meeting_upcoming',
    is_read: false,
    created_at: '2026-09-06T09:00:00.000Z'
  }
];

export const INITIAL_BATCHES: MailMergeBatch[] = [
  {
    id: 'batch-001',
    batch_number: 'ROS-MM-001',
    campaign_id: 'cmp-5',
    campaign_name: 'Care Campaign UK',
    brand_id: 'br-2',
    brand_name: 'John Academy',
    account_id: 'acc-2',
    account_name: 'Collab JA',
    sender_name: 'Farzan Hussain',
    lead_count: 2,
    created_by: 'usr-ruhit',
    created_by_name: 'Ruhit',
    created_at: '2026-08-25T10:00:00.000Z'
  }
];
